project:
  type: website
  output-dir: _site

website:
  title: "Jorge Piano Simões"
  site-url: "https://jpsimoes.github.io/personal-website"
  description: "Health Psychology, AI and Technology"
  favicon: img/portrait.png
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "Contact"
        href: contact.qmd
  page-footer: 
    left: "© 2025 Jorge Piano Simões"
    right: "Built with Quarto"
  open-graph: true
  twitter-card: true
  search: true
  repo-url: ""
  repo-actions: []

format:
  html:
    theme:
      - flatly
      - styles.scss
    toc: false
    smooth-scroll: true
    df-print: paged
    lightbox: true
    include-in-header:
      - fa.html

metadata-files:
  - _defaults.yml